Attribute VB_Name = "mdTlsThunks"
'=========================================================================
'
' Elliptic-curve cryptography thunks based on the following sources
'
'  1. https://github.com/esxgx/easy-ecc by Kenneth MacKay
'     BSD 2-clause license
'
'  2. https://github.com/ctz/cifra by Joseph Birr-Pixton
'     CC0 1.0 Universal license
'
'=========================================================================
Option Explicit
DefObj A-Z

'=========================================================================
' API
'=========================================================================

'--- for thunks
Private Const MEM_COMMIT                    As Long = &H1000
Private Const PAGE_EXECUTE_READWRITE        As Long = &H40
'--- for CryptAcquireContext
Private Const PROV_RSA_FULL                 As Long = 1
Private Const CRYPT_VERIFYCONTEXT           As Long = &HF0000000

Private Declare Sub CopyMemory Lib "kernel32" Alias "RtlMoveMemory" (Destination As Any, Source As Any, ByVal Length As Long)
Private Declare Sub FillMemory Lib "kernel32" Alias "RtlFillMemory" (Destination As Any, ByVal Length As Long, ByVal Fill As Byte)
Private Declare Function VirtualAlloc Lib "kernel32" (ByVal lpAddress As Long, ByVal dwSize As Long, ByVal flAllocationType As Long, ByVal flProtect As Long) As Long
Private Declare Function VirtualProtect Lib "kernel32" (ByVal lpAddress As Long, ByVal dwSize As Long, ByVal flNewProtect As Long, ByRef lpflOldProtect As Long) As Long
Private Declare Function CryptAcquireContext Lib "advapi32" Alias "CryptAcquireContextW" (phProv As Long, ByVal pszContainer As Long, ByVal pszProvider As Long, ByVal dwProvType As Long, ByVal dwFlags As Long) As Long
Private Declare Function CryptReleaseContext Lib "advapi32" (ByVal hProv As Long, ByVal dwFlags As Long) As Long
Private Declare Function CryptGenRandom Lib "advapi32" (ByVal hProv As Long, ByVal dwLen As Long, ByVal pbBuffer As Long) As Long

'=========================================================================
' Constants and member variables
'=========================================================================

Private Const STR_ECC_GLOB          As String = "////////////////AAAAAAAAAAAAAAAAAQAAAP////9LYNInPjzOO/awU8ywBh1lvIaYdlW967Pnkzqq2DXGWpbCmNhFOaH0oDPrLYF9A3fyQKRj5ea8+EdCLOHy0Rdr9VG/N2hAtsvOXjFrVzPOKxaeD3xK6+eOm38a/uJC409RJWP8wsq584SeF6et+ua8//////////8AAAAA/////5gvikKRRDdxz/vAtaXbtelbwlY58RHxWaSCP5LVXhyrmKoH2AFbgxK+hTEkw30MVXRdvnL+sd6Apwbcm3Txm8HBaZvkhke+78adwQ/MoQwkbyzpLaqEdErcqbBc2oj5dlJRPphtxjGoyCcDsMd/Wb/zC+DGR5Gn1VFjygZnKSkUhQq3JzghGy78bSxNEw04U1RzCmW7Cmp2LsnCgYUscpKh6L+iS2YaqHCLS8KjUWzHGeiS0SQGmdaFNQ70cKBqEBbBpBkIbDceTHdIJ7W8sDSzDBw5SqrYTk/KnFvzby5o7oKPdG9jpXgUeMiECALHjPr/vpDrbFCk96P5vvJ4ccYirijXmC+KQs1l7yORRDdxLztN7M/7wLW824mBpdu16Ti1SPNbwlY5GdAFtvER8VmbTxmvpII/khiBbdrVXhyrQgIDo5iqB9i+b3BFAVuDEoyy5E6+hTEk4rT/1cN9DFVviXvydF2+crGWFjv+sd6ANRLHJacG3JuUJmnPdPGbwdJK8Z7BaZvk4yVPOIZHvu+11YyLxp3BD2WcrHfMoQwkdQIrWW8s6S2D5KZuqoR0StT7Qb3cqbBctVMRg9qI+Xar32buUlE+mBAytC1txjGoPyH7mMgnA7DkDu++x39Zv8KPqD3zC+DGJacKk0eRp9VvggPgUWPKBnBuDgpnKSkU/C/S" & _
                                                "RoUKtycmySZcOCEbLu0qxFr8bSxN37OVnRMNOFPeY6+LVHMKZaiydzy7Cmp25q7tRy7JwoE7NYIUhSxykmQD8Uyh6L+iATBCvEtmGqiRl/jQcItLwjC+VAajUWzHGFLv1hnoktEQqWVVJAaZ1iogcVeFNQ70uNG7MnCgahDI0NK4FsGkGVOrQVEIbDcemeuO30x3SCeoSJvhtbywNGNaycWzDBw5y4pB40qq2E5z42N3T8qcW6O4stbzby5o/LLvXe6Cj3RgLxdDb2OleHKr8KEUeMiE7DlkGggCx4woHmMj+v++kOm9gt7rbFCkFXnGsvej+b4rU3Lj8nhxxpxhJurOPifKB8LAIce4htEe6+DN1n3a6njRbu5/T331um8Xcqpn8AammMiixX1jCq4N+b4EmD8RG0ccEzULcRuEfQQj9XfbKJMkx0B7q8oyvL7JFQq+njxMDRCcxGcdQ7ZCPsu+1MVMKn5l/Jwpf1ns+tY6q2/LXxdYR0qMGURsZXhwYW5kIDE2LWJ5dGUgawBleHBhbmQgMzItYnl0ZSBrAAAABQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPwAAAA=" ' 1160, 17.4.2020 22:16:51
Private Const STR_ECC_THUNK1        As String = "YCcAAIAqAAAwGQAAUBwAAAAgAABgIAAAEB4AANAgAABgIQAAoCAAAAAZAADAGAAA2IvlXcIEAMzMzMzMzMzMzOgAAAAAWIPoRYsAw8zMzMzoAAAAAFiD6FXDzMzMzMzMVYvsgeyoAAAAM8lWi3UQkIsEzgtEzgR1DUGD+QRy8V6L5V3CDABTV4t9DI2FYP///1dQ6EhOAACNhWD///9QjUXgUOgYRgAAi10IjUXgUFONRaBQ6NdLAACNRaBQjUWAUOj6RQAAjUXgUI1FoFDoDU4AAI1FoFCNReBQ6OBFAABWV41FoFDopUsAAI1FoFBX6MtFAABWjUWgUOjhTQAAjUWgUFbot0UAAOgy////VlNTi/joCEMAAAvCdQtXU+g9RAAAhcB4CFdTU+hxTwAA6Az///9WVlaL+OjiQgAAC8J1C1dW6BdEAACFwHgIV1ZW6EtPAADo5v7//1ZTVov46DxPAAALwnQIV1ZW6LBCAABWU41FoFDoFUsAAI1FoFBT6DtFAADotv7//1NTVov46IxCAAALwnULV1bowUMAAIXAeAhXVlbo9U4AAOiQ/v//VlNTi/joZkIAAAvCdQtXU+ibQwAAhcB4CFdTU+jPTgAAiwOD4AGDyAB0Hehg/v//UFNT6DhCAABTi/jokEwAAMHnHwl7HOsGU+iCTAAAU41FoFDo2EwAAI1FoFBW6K5EAADoKf7//4v4jUWAUFZW6HxOAAALwnQIV1ZW6PBBAADoC/7//4v4jUWAUFZW6F5OAAALwnQIV1ZW6NJBAADo7f3//4v4jUWAVlBQ6EBOAAALwnQLV41FgFBQ6LFBAACNRYBQU41FoFDoE0oAAI1FoFBT6DlEAADotP3//4v4jUXgUFNQ6AdOAAALwnQLV41F4FBQ" & _
                                                "6HhBAACLBokDi0YEi00MiUMEi0YIiUMIi0YMiUMMi0YQiUMQi0YUiUMUi0YYiUMYi0YciUMciwGJBotBBIlGBItBCIlGCItBDIlGDItBEIlGEItBFIlGFItBGIlGGItBHIlGHItF4IkBi0XkiUEEi0XoiUEIi0XsiUEMi0XwiUEQi0X0iUEUi0X4X4lBGItF/FuJQRxei+VdwgwAzFWL7FaLdQgzwA8fgAAAAACLDMYLTMYEdSVAg/gEcvEz0o1OIIsBC0EEdRNCg8EIg/oEcvC4AQAAAF5dwgQAM8BeXcIEAMzMzMzMzMzMzMzMVYvsgewkAQAAU4tdDFZX/3UUiwOJRbyLQwSJRcCLQwiJRcSLQwyJRciLQxCJRcyLQxSJRdCLQxiJRdSLQxyJRdiLQyCJhXz///+LQySJRYCLQyiJRYSLQyyJRYiLQzCJRYyLQzSJRZCLQziJRZSLQzyJRZiNhVz///9QjUWcUI2FfP///1CNRbxQ6GEHAACLfRBX6PhJAACD6AKJRRSFwH52M/aLyIPhPzPSD6vOg/kgD0PWM/KD+UAPQ9bB6AYjNMcjVMcEC/J1BY1GAesCM8DB4AWNnVz///8D2I1NnAPIjbV8////U/fYiU38UQPwjX28A/hWV+gUBAAAVldT/3X86EkCAACLRRSLfRBIiUUUhcB/jYtdDIsHg+ABg8gAdQe4AQAAAOsCM8DB4AWNjVz///8DyI1VnFED0IlNDI21fP///4lVFFIr8I19vCv4VlfouQMAAOhU+///iUUQjUWcUI1FvFCNRdxQ6KBLAAALwnQN/3UQjUXcUFDoDz8AAFaNRdxQjYUc////UOhuRwAAjYUc////UI1F3FDojkEAAFONRdxQjYUc////UOhNR" & _
                                                "wAAjYUc////UI1F3FDobUEAAOjo+v//UI1F3FBQ6B1EAACNQyBQjUXcUI2FHP///1DoGUcAAI2FHP///1CNRdxQ6DlBAABXjUXcUI2FHP///1Do+EYAAI2FHP///1CNRdxQ6BhBAABWV/91DP91FOgrAQAAjUXcUI2F3P7//1DoG0kAAI2F3P7//1CNhTz///9Q6OhAAACNhTz///9QjUWcUI2F3P7//1DooUYAAI2F3P7//1CNRZxQ6MFAAACNRdxQjYU8////UI2F3P7//1DoekYAAI2F3P7//1CNhTz///9Q6JdAAACNhTz///9QjYVc////UI2F3P7//1DoTUYAAI2F3P7//1CNhVz///9Q6GpAAACLTQiLRZxfXokBi0WgiUEEi0WkiUEIi0WoiUEMi0WsiUEQi0WwiUEUi0W0iUEYi0W4iUEci4Vc////iUEgi4Vg////iUEki4Vk////iUEoi4Vo////iUEsi4Vs////iUEwi4Vw////iUE0i4V0////iUE4i4V4////iUE8W4vlXcIQAMzMzMzMzMxVi+yD7GBTVlfoUvn//4tdCIv4i3UQjUXgU1ZQ6J9JAAALwnQLV41F4FBQ6BA9AACNReBQjUWgUOjDRwAAjUWgUI1F4FDolj8AAI1F4FBTjUWgUOhYRQAAjUWgUFPofj8AAI1F4FBWjUWgUOhARQAAjUWgUFboZj8AAOjh+P///3UMi30UV1eJRQjoMUkAAAvCdAr/dQhXV+ijPAAAV41FoFDoWUcAAI1FoFCNReBQ6Cw/AADop/j//4lFCI1F4FNQUOj5SAAAC8J0Df91CI1F4FBQ6Gg8AADog/j//4lFCI1F4FZQUOjVSAAAC8J0Df91CI1F4FBQ6EQ8AADoX/" & _
                                                "j//1NWVolFCOi0SAAAC8J0Cv91CFZW6CY8AABW/3UMjUWgUOiJRAAAjUWgUP91DOitPgAA6Cj4//+JRQiNReBQU1boekgAAAvCdAr/dQhWVujsOwAAVleNRaBQ6FFEAACNRaBQV+h3PgAA6PL3////dQyL2FdX6EZIAAALwnQIU1dX6Lo7AACLReCJBotF5IlGBItF6IlGCItF7IlGDItF8IlGEItF9IlGFItF+IlGGItF/F+JRhxeW4vlXcIQAMzMVYvsgezgAAAAU1ZX6I/3//+LdQiL+ItdEI1F4FZTUOjcRwAAC8J0C1eNReBQUOhNOwAAjUXgUI2FYP///1Do/UUAAI2FYP///1CNReBQ6M09AACNReBQVo2FYP///1DojEMAAI2FYP///1BW6K89AACNReBQU42FYP///1DobkMAAI2FYP///1BT6JE9AADoDPf///91DIt9FIlFCI1F4FdQ6Nk6AAALwnUQ/3UIjUXgUOgJPAAAhcB4Df91CI1F4FBQ6DhHAADo0/b///91DIlFCFdX6CZHAAALwnQK/3UIV1fomDoAAOiz9v//VolFCI1FgFNQ6AVHAAALwnQN/3UIjUWAUFDodDoAAI1FgFD/dQyNRaBQ6NRCAACNRaBQ/3UM6Pg8AADoc/b//1OJRQiNRYBWUOhFOgAAC8J1EP91CI1FgFDodTsAAIXAeA3/dQiNRYBQUOikRgAAV41FoFDo2kQAAI1FoFBT6LA8AADoK/b//4lFCI1FgFBTU+h9RgAAC8J0Cv91CFNT6O85AADoCvb//1OJRQiNRcBWUOhcRgAAC8J0Df91CI1FwFBQ6Ms5AACNRcBQV42FIP///1DoKkIAAI2FIP///1BX6E08AADoyPX//4tdDFN" & _
                                                "XV4lFCOgaRgAAC8J0Cv91CFdX6Iw5AACNReBQjYUg////UOg8RAAAjYUg////UI1FwFDoDDwAAOiH9f//i/iNRYBQjUXAUFDo10UAAAvCdAtXjUXAUFDoSDkAAOhj9f//i/iNRcBWUI1FgFDos0UAAAvCdAtXjUWAUFDoJDkAAI1F4FCNRYBQjYUg////UOiAQQAAjYUg////UI1FgFDooDsAAOgb9f//i/iNRYBTUFPobkUAAAvCdAhXU1Po4jgAAItFwIkGi0XEiUYEi0XIiUYIi0XMiUYMi0XQiUYQi0XUiUYUi0XYiUYYi0XcX4lGHF5bi+VdwhAAzMzMzMzMzMzMzFWL7IPsIItNFA9XwFOLXRBWi3UIV4t9DGYPE0XoiwaJA4tGBIlDBItGCIlDCItGDIlDDItGEIlDEItGFIlDFItGGIlDGItGHIlDHIsHiQGLRwSJQQSLRwiJQQiLRwyJQQyLRxCJQRCLRxSJQRSLRxiJQRiLRxyJQRyLTRhmDxNF8GYPE0X4x0XgAQAAAMdF5AAAAACFyXQviwGJReCLQQSJReSLQQiJReiLQQyJReyLQRCJRfCLQRSJRfSLQRiJRfiLQRyJRfyNReBQV1boPgEAAI1F4FBXVugD9P//jUXgUP91FFPoJgEAAF9eW4vlXcIUAMzMzMzMzMzMzMzMzMxTi0QkDItMJBD34YvYi0QkCPdkJBQD2ItEJAj34QPTW8IQAMzMzMzMzMzMzMzMzMyA+UBzFYD5IHMGD6XC0+DDi9AzwIDhH9PiwzPAM9LDzID5QHMVgPkgcwYPrdDT6sOLwjPSgOEf0+jDM8Az0sPMVYvsi0UQU1aLdQiNSHhXi30MjVZ4O/F3BDvQcwuNT3g78XcwO9dyLCv4" & _
                                                "uxAAAAAr8IsUOAMQi0w4BBNIBI1ACIlUMPiJTDD8g+sBdeRfXltdwgwAi9eNSBCL3ivQK9gr/rgEAAAAjXYgjUkgDxBB0A8QTDfgZg/UyA8RTuAPEEwK4A8QQeBmD9TIDxFMC+CD6AF10l9eW13CDADMzMzMzFWL7IPsYI1FoFb/dRBQ6D1BAACNRaBQjUXgUOgQOQAAi3UIjUXgUFaNRaBQ6M8+AACNRaBQVuj1OAAA/3UQjUXgUI1FoFDotT4AAI1FoFCNReBQ6Ng4AACLdQyNReBQVo1FoFDolz4AAI1FoFBW6L04AABei+VdwgwAzMzMzMzMVYvsg+wgU1aLdQgzyVeJTeyBBM4AAAEAiwTOg1TOBACLXM4ED6zYEMH7EIlF6IP5D3UVx0X8AQAAAIvQx0XwAAAAAIld+OsiD1fAZg8TRfSLRfiJRfCLRfRmDxNF4ItV4IlF/ItF5IlF+IP5D415AWoAG8D32A+vxytV/GoljTTGi0X4G0XwUFLo4v3//4tN6APBE9OD6AGD2gABBotF7BFWBIt1CA+kyxDB4RApDMaLz4lN7BlcxgSD+RAPgk////9fXluL5V3CBADMzMzMzFWL7IPsEFOLXRgzyYlN/IXbD4SRAAAAi1UQVleLfQzHRfABAAAAiweL8ivwiUX0O94PQvOFyXU7i30IA/iJffiLfQyF9nQsD7ZFFIvOi334i9lpwAEBAQHB6QKLVRDzq4vLi10Yg+ED86qLRfSLTfyLfQyFwHUJO/IPRE3wiU38A8Y7wnUU/3UI/3Ug/1Uci1UQxwcAAAAA6wIBN4tN/CveiV0YdYBfXluL5V3CHADMVYvsV4t9IIvHg+gAdGKD6AEPhLUAAABTVoPoAXRyi10ojUUUi3UkU" & _
                                                "1ZWagFQ/3UQ/3UM/3UI6MUAAACLTRhTVjhNHHQwjUf+i30QUFFX/3UM/3UI6Pf+//9TVlZqAY1FHFBX/3UM/3UI6JIAAABeW19dwiQAjUf/i30QUFFX/3UM/3UI6Mf+//9eW19dwiQA/3Uoi0Uki10Qi30Mi3UIUFBqAY1FFFBTV1boUQAAAP91KItFJFBQagGNRRxQU1dW6DsAAABeW19dwiQA/3UoikUcMEUUi0UkUFBqAY1FFFD/dRD/dQz/dQjoEgAAAF9dwiQAzMzMzMzMzMzMzMzMzFWL7ItNDIPsCItVJIM5AFOLXRRWi3UQV4t9GHRthf90aYvGi98rATvHD0LYiwEDRQiJXRiLXRSJRfyLRRiFwHQji1X8i/CLy4oBjVIBiEL/jUkBg+4BdfCLdRCLTQyLVSSLRRgBAQPYK/g5MXUc/3UIUoX/dQX/VSDrA/9VHItFDItVJMcAAAAAADv+chtmkFNSO/51Bf9VIOsD/1Uci1UkK/4D3jv+c+eF/3REi00MiwmLxot1CCvBO8eL1w9C0APxiVUki8OF0nQVDx9EAACKCI12AYhO/41AAYPqAXXwi00Mi0UkA9iLdRABASv4db9fXluL5V3CIADMzMzMzMxVi+yLTRyD7AhXi30Yhcl0dlOLXQxWgzsAdRH/dQj/dST/VSCLRRCLTRyJA4sDi/GLVRAr0DvBiVUYD0LwM8CJdfyF9nQvi10UK9+JXfhmkIt1/I0UOIoME4tVGANVCItd+DIMAo0UOECICjvGcuGLXQyLTRwpMyvOAXUUA/6JTRyFyXWRXltfi+VdwiAAzMxVi+yD7GyLTRRTVlcPtlkDD7ZBAg+2UQfB4gjB4wgL2A+2QQHB4wgL2A+2AcHjCAvYD7ZBBg" & _
                                                "vQiV3YweIID7ZBBQvQD7ZBBMHiCAvQD7ZBColV9IlV1A+2UQvB4ggL0A+2QQnB4ggL0A+2QQjB4ggL0A+2QQ6JVfCJVdAPtlEPweIIC9APtkENweIIC9APtkEMi00IweIIC9CJVfgPtkECiVXMD7ZRA8HiCAvQD7ZBAcHiCAvQD7YBweIIC9APtkEGiVXsiVXID7ZRB8HiCAvQD7ZBBcHiCAvQD7ZBBMHiCAvQD7ZBColV6IlVxA+2UQvB4ggL0MHiCA+2QQkL0A+2QQjB4ggL0A+2QQ6JVeSJVcAPtlEPweIIC9APtkENweIIC9APtkEMi00MweIIC9CJVeAPtkECiVW8D7ZRA8HiCAvQD7ZBAcHiCAvQD7YBweIIC9APtkEGiVUIiVW4D7ZRB8HiCAvQD7ZBBcHiCAvQD7ZBBMHiCAvQD7ZBColVFIlVtA+2UQvB4ggL0A+2QQnB4ggL0A+2QQjB4ggL0A+2QQ6JVQyJVbAPtlEPweIIC9APtkENweIIC9APtkEMweIIC9CJVfyJVayLVRAPtkoDD7ZCAsHhCAvID7ZCAcHhCAvID7YCweEIC8iJTdyJTagPtnIHD7ZCBg+2egsPtkoOweYIC/DB5wgPtkIFweYIC/DHRZgKAAAAD7ZCBMHmCAvwD7ZCCgv4iXWkD7ZCCcHnCAv4D7ZCCMHnCAv4D7ZCD8HgCAvBiX2gD7ZKDcHgCAvBD7ZKDItV3MHgCAvBi03siUWc6wOLXRAD2YtNCDPTiV0QwcIQA8qJTQgzTezBwQwD2TPTiV0Qi10IwcIIA9qJVdyLVfQDVegz8oldCDPZwcYQi00UA87BwweJTRQzTejBwQwD0TPyiVX0i1UUwcYIA9aJdeyLdfADdeQz/olVFDPRwcc" & _
                                                "Qi00MA8/BwgeJTQwzTeTBwQwD8TP+iXXwi3UMwccIA/eJfZSLffgDfeAzx4l1DDPxwcAQi038A8jBxgeJTfwzTeDBwQwD+TPHiX34i338wcAIA/iJffwz+YtNEAPKwccHM8GJTRCLTQzBwBADyIlNDDPKi1UQwcEMA9EzwolVEItVDMHACAPQiVUMM9GLTfQDzsHCB4lN9IlV6ItV3DPRi038wcIQA8qJTfwzzot19MHBDAPxM9aJdfSLdfzBwggD8ol1/DPxi03wA8/BxgeJTfCJdeSLdewz8YtNCMHGEAPOiU0IM8+LffDBwQwD+TP3iX3wi30IwcYIA/6JfQgz+YtN+APLwccHiX3gi32UM/mJTfiLTRTBxxADz4lNFDPLi134wcEMA9kz+4ld+MHHCAF9FItdFDPZi8uJXezBwQeDbZgBi134iU3sD4VA/v//AUWcAV3Mi03YA00QAVWoi1UYiU3Yi13Yi8OLTdQDTfSIGolN1ItN0ANN8MHoCIhCAYvDiU3Qi03sAU3Ii03EA03owegQiEICwesYiFoDi13Ui8OIWgTB6AiIQgWLw4lNxItNwANN5MHoEIhCBolNwItNvANN4AF1pAF9oMHrGIhaB4td0IvDiFoIiU28i024A00IwegIiEIJi8OJTbiLTbQDTRTB6BCIQgrB6xiIWguLXcyLw4lNtItNsANNDIhaDMHoCIhCDYvDiU2wi02sA038wegQiEIOwesYiFoPi13Ii8OJTayIWhDB6AiIQhGLw8HoEIhCEsHrGIhaE4tdxIvDiFoUwegIiEIVi8PB6BCIQhbB6xiIWheLXcCLw4haGMHoCIhCGYvDwegQiEIawesYiFobi128i8OIWhzB6AiIQh2Lw8HoEIhCHsHr" & _
                                                "GIhaH4tduIvDiFogwegIiEIhi8PB6BCIQiLB6xiIWiOLXbSLw4haJMHoCIhCJYvDwegQiEImwesYiFoni12wi8OIWijB6AiIQimLw8HoEIhCKsHrGIhaK4vZiFosi8PB6AiIQi2Lw8HoEIhCLsHrGIhaL4tdqIvDiFowwegIiEIxjUo8i8PB6xjB6BCIQjKIWjOLXaSLw4haNMHoCIhCNYvDwegQiEI2wesYiFo3i12gi8OIWjjB6AiIQjmLw8HoEIhCOsHrGIhaO4tVnIvCwegIiBGIQQGLwl/B6BDB6hheiEECiFEDW4vlXcIUAMxVi+xWi3UIV/91DP92MI1+IFeNRhBQVuiE+f//i1Z4M8CABwF1C0A7wnQGgAQ4AXT1X15dwggAzMzMzMzMzMzMVYvsg+wQi0UgDxAAjUXwUGoA/3UkDxFF8P91HP91GP91FP91EP91DP91COgwHgAAi+VdwiAAzMzMzMzMzMzMzFWL7P91JGoB/3Ug/3Uc/3UY/3UU/3UQ/3UM/3UI6P4dAABdwiAAzMzMzMzMzMzMzFWL7IHsKAQAAFNWV2pwjYXo/P//x4XY/P//QdsAAGoAUMeF3Pz//wAAAADHheD8//8BAAAAx4Xk/P//AAAAAOjsEwAAi3UMjYVg////ah9WUOiqEwAAikYfg8QYgKVg////+CQ/DECIhX////+Nhdj7////dRBQ6KQpAAAPV8CNtVj+//9mDxOFWP7//429YP7//7keAAAAZg8TRYDzpbkeAAAAZg8TheD+//+NdYDHhVj+//8BAAAAjX2Ix4Vc/v//AAAAAPOluR4AAADHRYABAAAAjbXg/v//x0WEAAAAAI296P7//7v+AAAA86W5IAAAAI212Pv//4292P3//" & _
                                                "/Oli8OKy8H4A4DhB4qEBWD////S6CQBD7bAmYvwjYXY/f//VlCNRYBQ6KMhAABWjYVY/v//UI2F4P7//1DojyEAAI2F4P7//1CNRYBQjYVY/f//UOho8v//jYXg/v//UI1FgFBQ6BcoAACNhVj+//9QjYXY/f//UI2F4P7//1DoPfL//42FWP7//1CNhdj9//9QUOjpJwAAjYVY/f//UFCNhVj+//9Q6MUTAACNRYBQUI2FWPz//1DotBMAAI1FgFCNheD+//9QjUWAUOigEwAAjYVY/f//UI2F2P3//1CNheD+//9Q6IYTAACNheD+//9QjUWAUI2FWP3//1Dov/H//42F4P7//1CNRYBQUOhuJwAAjUWAUFCNhdj9//9Q6E0TAACNhVj8//9QjYVY/v//UI2F4P7//1DoQycAAI2F2Pz//1CNheD+//9QjUWAUOgcEwAAjYVY/v//UI1FgFBQ6Fvx//+NRYBQjYXg/v//UFDo+hIAAI2FWPz//1CNhVj+//9QjUWAUOjjEgAAjYXY+///UI2F2P3//1CNhVj+//9Q6MkSAACNhVj9//9QUI2F2P3//1DotRIAAFaNhdj9//9QjUWAUOgEIAAAVo2FWP7//1CNheD+//9Q6PAfAACD6wEPiRj+//+NheD+//9QUOjqDgAAjYXg/v//UI1FgFBQ6GkSAACNRYBQ/3UI6I0VAABfXluL5V3CDADMzMzMVYvsg+wgjUXgxkXgCVD/dQwPV8DHRfkAAAAA/3UIDxFF4WbHRf0AAGYP1kXxxkX/AOiq/P//i+VdwggAzMzMzFWL7IPsRFaLdQhXg76oAAAAAHQGVujWFwAAM8kPH0AAD7aEDogAAACJRI28QYP5EHLuU1bHRfwAAAAA6J" & _
                                                "AWAAAzyY1dvIvWK96NeREPH0AAiwQTjVIEA0L8A8gPtsHB6QiJQvyD7wF154tVDDPAW5CKDIaIDBBAg/gQcvQzwIv+uSsAAADzq4oGX16L5V3CCADMzMzMzMzMzMzMzMzMzMxVi+yLVQgzwFZXi/qLdRC5KwAAAPOri00MD7YBiUJED7ZBAYlCSA+2QQKJQkwPtkEDg+APiUJQD7ZBBCX8AAAAiUJUD7ZBBYlCWA+2QQaJQlwPtkEHg+APiUJgD7ZBCCX8AAAAiUJkD7ZBCYlCaA+2QQqJQmwPtkELg+APiUJwD7ZBDCX8AAAAiUJ0D7ZBDYlCeA+2QQ6JQnwPtkEPg+APx4KEAAAAAAAAAImCgAAAAI2CiAAAALoQAAAAK/APHwCKDAaNQAGISP+D6gF18l9eXcIMAMzMzMzMzMzMzMzMzFWL7IPsGFNWu/B8CwCB6wBACwBXiV386CTi////dQi5QAAAAI00A4tFCFaLdQiNWGSLQGD34QMDi/qLVQiL2IPXAIPACIPgP4PGZCvIg8IgUWoAagBogAAAAGpAD6TfA1ZSweMDiX346BPx//+Lx4hd78HoGIvLiEXoi8fB6BCIRemLx8HoCIhF6opF+IhF64vHD6zBGMHoGIhN7IvHi8sPrMEQwegQi8OITe0PrPgIwe8IiEXu6IXh//8DRfyLXQhTUFBqCI1F6FBqQFaNQyBQ6Krx//+LE4vCi3UMwegYiAaLwsHoEIhGAYvCwegIiEYCiFYDi0sEi8HB6BiIRgSLwcHoEIhGBYvBwegIiEYGiE4Hi0sIi8HB6BiIRgiLwcHoEIhGCYvBwegIiEYKiE4Li0sMi8HB6BiIRgyLwcHoEIhGDYvBwegIiEYOiE4Pi0sQi8HB6BiIRhC" & _
                                                "LwcHoEIhGEYvBwegIiEYSiE4Ti0sUi8HB6BiIRhSLwcHoEIhGFYvBwegIiEYWiE4Xi0sYi8HB6BiIRhiLwcHoEIhGGYvBwegIiEYaiE4bi0sci8HB6BiIRhyLwcHoEIhGHQ9XwIvBwegIiEYeiE4fDxEDXw8RQxBeDxFDIA8RQzAPEUNADxFDUGYP1kNgW4vlXcIIAMxVi+yLRQgPV8APEQAPEUAQDxFAIA8RQDAPEUBADxFAUGYP1kBgxwBn5glqx0AEha5nu8dACHLzbjzHQAw69U+lx0AQf1IOUcdAFIxoBZvHQBir2YMfx0AcGc3gW13CBABVi+zo6N///7nwfAsAgekAQAsAA8GLTQhRUFD/dRCNQWT/dQxqQFCNQSBQ6ADw//9dwgwAzMzMzMzMzMzMzMzMVYvsg+xAjUXAUP91COjuAAAAajCNRcBQ/3UM6HAMAACDxAyL5V3CCADMzMzMzMzMVYvsi1UIuTIAAABXM8CL+vOrxwLYngXBx0IEXZ27y8dCCAfVfDbHQgwqKZpix0IQF91wMMdCFFoBWZHHQhg5WQ73x0Ic2OwvFcdCIDELwP/HQiRnJjNnx0IoERVYaMdCLIdKtI7HQjCnj/lkx0I0DS4M28dCOKRP+r7HQjwdSLVHX13CBADMzMzMzMzMzMzMVYvs6Oje//+5wH4LAIHpAEALAAPBi00IUVBQ/3UQjYHEAAAA/3UMaIAAAABQjUFAUOj67v//XcIMAMzMzMzMzFWL7IPsHItVCFNWjYrEAAAAu8B+CwCLgsAAAABXv4AAAAD354vwAzGLxoPSAIHrAEALAA+kwgPB4AOJVfyJRfiJVfToaN7//4tVCAPDUlCNRhCD4H+NssQAAAAr+I1KQFdqAGoAaIAA" & _
                                                "AABogAAAAFZR6Hrt///HReQAAAAAx0XoAAAAAOgn3v//i1UIA8NSUFBqCI1F5FBogAAAAFaNckBW6Eru//+LffyLx4tV+IvKwegYiEXki8fB6BCIReWLx8HoCIhF5opF9IhF54vHD6zBGIhV68HoGIhN6IvHi8oPrMEQwegQi8KITekPrPgIwe8IiEXq6Lbd//8Dw4tdCFNQUGoIjUXkUGiAAAAAjYPEAAAAUFbo1u3//4sLi1sEi8OLfQzB6BiLVQiJTfyIB4vDwegQiEcBi8PB6AiIRwKLww+swRiIXwPB6BiITwSLw4tN/A+swRDB6BCITwWLTfyLwQ+s2AiIRwaITwfB6wiLWgiLy4tSDIvCwegYiEcIi8LB6BCIRwmLwsHoCIhHCovCD6zBGIhXC8HoGIhPDIvCi8sPrMEQwegQiE8Ni8MPrNAIiEcOi0UIiF8PweoIi1gQi1AUi8LB6BiIRxCLwsHoEIhHEYvCwegIi8uIRxKLwg+swRiIVxPB6BiITxSLwovLD6zBEMHoEIhPFYvDD6zQCIhHFotFCIhfF8HqCItYGIvLi1Aci8LB6BiIRxiLwsHoEIhHGYvCwegIiEcai8IPrMEYiFcbwegYiE8ci8KLyw+swRDB6BCITx2Lww+s0AiIRx6LRQiIXx/B6giLWCCLy4tQJIvCwegYiEcgi8LB6BCIRyGLwsHoCIhHIovCD6zBGIhXI8HoGIhPJIvCi8sPrMEQwegQi8OITyUPrNAIiEcmi0UIweoIiF8ni1goi1Asi8LB6BiIRyiLwsHoEI13OIhHKYvLi8LB6AiIRyqLwg+swRiIVyvB6BiITyyLwovLD6zBEMHoEIhPLYvDD6zQCIhHLotFCIhfL8HqCItYMIvLi1A0i"
Private Const STR_ECC_THUNK2        As String = "8LB6BiIRzCLwsHoEIhHMYvCwegIiEcyi8IPrMEYiFcziE80i8vB6BiLwg+swRDB6BCITzWLww+s0AiIRzaIXzeLfQjB6giLVzyLwotfOIvLwegYiAaLwsHoEIhGAYvCwegIiEYCi8IPrMEYiFYDwegYiE4Ei8KLyw+swRDB6BCLw4hOBQ+s0Ai5MgAAAIhGBsHqCDPAiF4H86tfXluL5V3CCADMzMzMzMzMVYvsU4tdDFZXi30ID7ZDGJmLyIvyD6TOCA+2QxnB4QiZC8gL8g+kzggPtkMaweEImQvIC/IPpM4ID7ZDG8HhCJkLyAvyD7ZDHA+kzgiZweEIC/ILyA+2Qx0PpM4ImcHhCAvyC8gPtkMeD6TOCJnB4QgL8gvID7ZDHw+kzgiZweEIC/ILyIl3BIkPD7ZDEJmLyIvyD7ZDEQ+kzgiZweEIC/ILyA+2QxIPpM4ImcHhCAvyC8gPtkMTD6TOCJnB4QgL8gvID7ZDFA+kzgiZweEIC8gL8g+kzggPtkMVweEImQvIC/IPpM4ID7ZDFsHhCJkLyAvyD6TOCA+2QxfB4QiZC8gL8olPCIl3DA+2QwiZi8iL8g+kzggPtkMJweEImQvIC/IPtkMKD6TOCJnB4QgL8gvID7ZDCw+kzgiZweEIC/ILyA+2QwwPpM4ImcHhCAvyC8gPtkMND6TOCJnB4QgL8gvID7ZDDg+kzgiZweEIC/ILyA+2Qw8PpM4ImcHhCAvyC8iJdxSJTxAPtgOZi8iL8g+2QwEPpM4ImcHhCAvyC8gPtkMCD6TOCMHhCJkLyAvyD7ZDAw+kzgiZweEIC/ILyA+2QwQPpM4ImcHhCAvyC8gPtkMFD6TOCJnB4QgL8gvID7ZDBg+kzgiZweEIC/ILyA+2Qw" & _
                                                "cPpM4ImcHhCAvIC/KJdxyJTxhfXltdwggAzMzMVYvsg+xgjUXg/3UMUOje/f//M8CLTMXgC0zF5HUOQIP4BHLwM8CL5V3CCACNReBQ6KvY//+D6IBQ6MIdAACD+AF0E+iY2P//g+iAUI1F4FBQ6OooAABqAI1F4FDof9j//4PAQFCNRaBQ6MLb//+NRaBQ6Gnb//+FwHWpikXAi00IJAEEAogBjUWgUI1BAVDoDAAAALgBAAAAi+VdwggAzFWL7FaLdQixKFeLfQwPtkcHiEYYD7ZHBohGGYsHi1cE6Kvk//+IRhqxIIsHi1cE6Jzk//+IRhuLD4tHBA+swRiIThyLD8HoGItHBA+swRCITh2LD8HoEItHBA+swQiITh6xKMHoCA+2B4hGHw+2Rw+IRhAPtkcOiEYRi0cIi1cM6Evk//+IRhKxIItHCItXDOg75P//iEYTi08Ii0cMD6zBGIhOFItPCMHoGItHDA+swRCIThWLTwjB6BCLRwwPrMEIiE4WsSjB6AgPtkcIiEYXD7ZHF4hGCA+2RxaIRgmLRxCLVxTo5uP//4hGCrEgi0cQi1cU6Nbj//+IRguLTxCLRxQPrMEYiE4Mi08QwegYi0cUD6zBEIhODYtPEMHoEItHFA+swQiITg6xKMHoCA+2RxCIRg8PtkcfiAYPtkceiEYBi0cYi1cc6ILj//+IRgKxIItHGItXHOhy4///iEYDi08Yi0ccD6zBGMHoGIhOBItPGItHHA+swRDB6BCITgWLTxiLRxwPrMEIwegIiE4GD7ZHGF+IRgdeXcIIAMzMVYvsg+xgi0UMD1fAU1ZXi30IQFBXx0XgAwAAAMdF5AAAAAAPEUXoZg/WRfjof/v//1eNRaBQ6AUlAACNRaBQjXc" & _
                                                "gVujYHAAA6FPW//+L2I1F4FBWVuimJgAAC8J0CFNWVugaGgAAV1aNRaBQ6H8iAACNRaBQVuilHAAA6CDW//+L+OgZ1v//g8AgUFZW6O4ZAAALwnULV1boIxsAAIXAeAhXVlboVyYAAFboQQMAAItNDDP/igGLDiQBD7bAg+EBmTvIdQQ7+nQNVujR1f//UFboKiYAAF9eW4vlXcIIAMxVi+yB7KAAAACNhWD/////dQhQ6Aj/////dQyNRaBQ6Kz6//9qAI1FoFCNhWD///9QjUXAUOjW2P//jUXAUP91EOg6/f//M8kPH4QAAAAAAItEzcALRM3EdR5Bg/kEcvCLTMXgC0zF5HUOQIP4BHLwM8CL5V3CDAC4AQAAAIvlXcIMAMzMzMzMzMzMzMzMzMxVi+yB7IQBAABTVot1DLkgAAAAV429fP7//7v9AAAA86WJXfiNhXz+//9QUFDoXgMAAIP7Ag+EvQEAAIP7BA+EtAEAAItFDI21/P7//w9XwI29BP///4PAEGYPE4X8/v//uTwAAACJRfTzpTPbDx8AjbUE////x0X8BAAAAIv4A/P/tB2A/v///7QdfP7///939P938OjW4P///7QdgP7//wFG+P+0HXz+//8RVvz/d/z/d/jot+D///+0HYD+//8BBv+0HXz+//8RVgT/dwT/N+ia4P///7QdgP7//wFGCP+0HXz+//8RVgz/dwz/dwjoe+D//wFGEI1/IBFWFI12IINt/AEPhXb///+LRfSDwwiB+4AAAAAPglP///8z9pBqAGom/3T1gP+09Xz////oPOD//wGE9fz+//9qABGU9QD///9qJv909Yj/dPWE6B3g//8BhPUE////agARlPUI////aib/dPWQ/3T1jOj+" & _
                                                "3///AYT1DP///2oAEZT1EP///2om/3T1mP909ZTo39///wGE9RT///9qABGU9Rj///9qJv909aD/dPWc6MDf//8BhPUc////EZT1IP///4PGBYP+Dw+CVv///42FfP7//7kgAAAAjbX8/v//jb18/v//86VQ6Bfh//+NhXz+//9Q6Avh//+LXfiD6wGJXfgPiSD+//+LfQiNtXz+//+5IAAAAPOlX15bi+VdwggAzMzMVYvsi0UIi9BWi3UQhfZ0FVeLfQwr+IoMF41SAYhK/4PuAXXyX15dw8zMzMzMzMzMVYvsi00Qhcl0Hw+2RQxWi/FpwAEBAQFXi30IwekC86uLzoPhA/OqX16LRQhdw8zMVYvsgeyAAAAAU1YPV8DHRcABAAAAV41FwMdFxAAAAAC7AQAAAGYP1kXYUA8RRciJXeDHReQAAAAADxFF6GYP1kX46GnS//9QjUXAUOg/FgAAjUXAUOg2IAAAi30IjXD/O/N2aY1F4FCNRYBQ6N8gAACNRYBQjUXgUOiyGAAAM9IzyYvGg+A/D6vCg/ggD0PKM9GD+ECLxg9DysHoBiNUxcAjTMXEC9F0G1eNReBQjUWAUOhJHgAAjUWAUI1F4FDobBgAAE6D/gF3motd4ItF5IlHBItF6IlHCItF7IlHDItF8IlHEItF9IlHFItF+IlHGItF/IkfiUccX15bi+VdwgQAzMzMzMzMzMzMzMzMzMxVi+yB7BQBAACLRQwPV8BTVle5PAAAAGYPE4Xs/v//jbXs/v//x0X8EAAAAI299P7///Oli00QjZ30/v//g8EQi9MrwolN+IlFDGYPH0QAAIv5x0UQBAAAAIvzDx9EAAD/dBgE/zQY/3f0/3fw6G7d//8BRviLRQwRVvz/d" & _
                                                "BgE/zQY/3f8/3f46FPd////dwQBBotFDP83EVYE/3QYBP80GOg63f//AUYIi0UMEVYM/3QYBP80GP93DP93COgf3f//AUYQjX8gi0UMEVYUjXYgg20QAXWKi034g8MIg238AQ+Fav///zP2Dx+EAAAAAABqAGom/7T1cP////+09Wz////o2dz//wGE9ez+//9qABGU9fD+//9qJv+09Xj/////tPV0////6LTc//8BhPX0/v//agARlPX4/v//aib/dPWA/7T1fP///+iS3P//AYT1/P7//2oAEZT1AP///2om/3T1iP909YToc9z//wGE9QT///9qABGU9Qj///9qJv909ZD/dPWM6FTc//8BhPUM////EZT1EP///4PGBYP+Dw+CSv///4tVCI217P7//7kgAAAAi/rzpTPJiU34Dx8AgQTKAAABAIsEyoNUygQAi1zKBA+s2BDB+xCJRfSD+Q91FcdFDAEAAACL0MdF/AAAAACJXRDrIg9XwGYPE0Xsi0XwiUX8i0XsZg8TReSLVeSJRQyLReiJRRCD+Q+NeQGLTQgbwPfYD6/HK1UMagBqJY00wYtFEBtF/FBS6KDb//+LTfQDwRPTg+gBg9oAAQaLRfgRVgSLVQgPpMsQiX34weEQKQzCi88ZXMIEg/kQD4JM////Uuj23P//X15bi+VdwgwAzMzMzMzMzMzMzMzMzFWL7IPsEFNWi3UMV4t9GGoAVmoA/3UU6DTb//9qAFZqAFeJRfCL2ugk2///agD/dRCJRfSL8moAV+gS2///agD/dRCJRfxqAP91FIlV+Oj92v//i/iLRfQD+4PSAAP4E9Y71ncOcgQ7+HMIg0X8AINV+AGLRQgzyQtN8IkIM8kDVfyJeAQTTfhfXo" & _
                                                "lQCIlIDFuL5V3CFADMzMzMzMzMzMxVi+yB7AgBAACNhXj///+5IAAAAFNWi3UMV429eP////OlUOgY3P//jYV4////UOgM3P//jYV4////UOgA3P//jb34/v//uwIAAAAPH0QAAIuNeP///4uFfP///4Hp7f8AAImN+P7//4PYAImF/P7//7gIAAAAZmYPH4QAAAAAAIt0B/iLTAf8i5QFeP///4l1+A+szhCLjAV8////g+YBx0QH/AAAAAAr1oPZAIHq//8AAImUBfj+//+D2QCJjAX8/v//D7dN+IlMB/iDwAiD+HhyrIuNaP///4uFbP///4tV8A+swRAPt4Vo////g+EBiYVo////K9HHhWz///8AAAAAi030uAEAAACD2QCB6v9/AACJlXD///+D2QCJjXT///8PrMoQg+IBwfkQK8JQjYX4/v//UI2FeP///1Do7QgAAIPrAQ+FBP///4t1CDPSioTVeP///4uM1Xj///+IBFaLhNV8////D6zBCIhMVgFCwfgIg/oQctdfXluL5V3CCADMzMzMzMzMzMzMzMzMVYvsg+xIU1ZXi30IDxAHi0dAiUX4DxFFuA8QRxAPEUXIDxBHIA8RRdgPEEcwDxFF6OiqzP//M8kz0o2wRAQAAI1FuCvwjQSWi0QFuANElbgDyA+2wYlElbhCwekIg/oRfOOLRfiNdcj30LoCAAAAJYAAAACNWP/30MHoH8HrHyPY99uLw/fQiUX8Zg9uw2YPcNgAZg9uwIvHi89mD3DgAI19uCv5K/FmDx+EAAAAAACNQCAPEEDgDxBMB+BmD9vDZg/bzGYP68gPEFQG4A8RSOAPKMtmD9vUDxBA8GYP28hmD+vRDxFQ8IPqAXXDjUFAjXIBiwiNQAS" & _
                                                "LVDj8I8sjVfwL0YlQ/IPuAXXoX15bi+VdwgQAzMzMzMzMzMzMzMzMVYvsg+xEjUW8U1ZXakRqAFDoyvj//4t1CIPEDDPJi5aoAAAAhdJ0GQ8fhAAAAAAAD7aEDpgAAACJRI28QTvKcu8zycdElbwBAAAAjV28i9Yr3o15EYsEE41SBANC/APID7bBwekIiUL8g+8BdeeNRkRQVugYAAAAX15bi+VdwgQAzMzMzMzMzMzMzMzMzMzMVYvsg+xUi0UMjU2sU1aLdQgz2yvBx0X4EAAAAFeJRfAz0jP/M8CJVQiJVfyF23hRjUsBg/kCfDCLTfCNVayNDJkD0YsMho1S+A+vSggBTQiLTIYEg8ACD69KBAFN/I1L/zvBft6LVQg7w38Oi30Mi8sryIs8jw+vPIaLRfwDwgP4jUMBM9KJVQiLyIlV/IlF9IP4EX1yg334AnxDi1UMi8MrwY0UgoPCQA8fgAAAAACLBI6NUvgPr0IMjQSAweAGAUUIi0SOBIPBAg+vQgiNBIDB4AYBRfyD+RB81ItVCIP5EX0ai1UMi8MrwYtEgkQPrwSOi1UIjQSAweAGA/iLRfwDwgP4i0X0i034SYl8nayJTfiL2IP5/w+PAv///zPJM9IDTJWsD7bBiUSVrELB6QiD+hB87ANN7IvBwekCg+ADM9KJReyNDIkPH4AAAAAAA0yVrA+2wYlElaxCwekIg/oQfOwPEEWsi0XsA8EPEQZfDxBFvA8RRhAPEEXMDxFGIA8QRdwPEUYwiUZAXluL5V3CCADMzMzMzMzMzMzMzMxVi+yLVQyD7EQzwA8fRAAAD7YMEIlMhbxAg/gQfPJTi10IM8lWV419vMdF/AEAAACL041xESv7iwQXjVIEA0L8A8gPtsHB" & _
                                                "6QiJQvyD7gF1541DRFBT6Ab+//9fXluL5V3CCADMzMzMzMzMzMzMzMzMVYvsgex8AQAAi0UMD1fAZg/WRd3HReUAAAAAZsdF6QAA8w9+AItACMZF6wBmD9ZF4A9XwIlF6ItFCA8RRb1TZg/WRc0PEABWVw8RhTD////GRdwADxBAEMZFvADHRdUAAAAAZsdF2QAAxkXbAA8RhUD////op8j//w8QRdy7gFgLAMdFpAAAAAAFMQQAAMdFqAQAAACB6wBACwCJhWD///8PEYVQ////iV0M6IDI//8Dw42NMP///1FQaiCNRbxQUGpAjUWkUI2FZP///1Dondn//41FzFCNRbxQjYWE/v//UOgp5f//D1fADxFFvIpFvA8RRczoNsj//wPDjY0w////UVBqII1FvFBQakCNRaRQjYVk////UOhT2f//D1fADxFFvIpFvA8RRcy+sHYLAMZF7ABmD9ZF7YHuAEALAMdF9QAAAABmx0X5AADGRfsA6NvH//+LfRSNjYT+//9RA8ZQUFf/dRCNhSz///9qEFCNhRz///9Q6PTX///or8f//wPGjY2E/v//UVBQi8f32IPgD1CNRexQahCNhSz///9QjYUc////UOjD1///6H7H//+DfSQBdVCLfSCNjTD///9RA8OLXRxQU1f/dRiNRaRqQFCNhWT///9Q6JHY///oTMf//wPGjY2E/v//UVBQU1dqEI2FLP///1CNhRz///9Q6GrX///rKotdHI2NhP7//1EDxlBQU/91GI2FLP///2oQUI2FHP///1DoQdf//4t9IOj5xv//A8aNjYT+//9RUFCLw/fYg+APUI1F7FBqEI2FLP///1CNhRz///9Q6A3X//+LRRQz0ohF7IvIi8KJVegPr" & _
                                                "MEIiF30wegIiE3ti8KLTRQPrMEQwegQiE3ui8KLTRQPrMEYwegYD7bCiEXwi8LB6AiIRfGLwsHoEIhF8sHqGIhN74vLiFXzM9KLwolV6A+swQjB6AiITfWLwovLD6zBEMHoEIhN9ovCi8sPrMEYwegYD7bCiEX4i8LB6AiIRfmLwsHoEMHqGIhN94hF+ohV++gnxv//jY2E/v//A8ZRUFBqEI1F7FBqEI2FLP///1CNhRz///9Q6EHW//+DfSQBdSb/dSiNhYT+//9Q6Czi//8PV8APEYUw////ioUw////M8DptgAAAI1FrFCNhYT+//9Q6AXi//+LdSiNRayLyDLbuhAAAAAr8Q8fQACKDAaNQAEySP8K2YPqAXXwhNt1ReiXxf//A0UMjY0w////UYtNHFBRV/91GI1FpGpAUI2FZP///1Dostb//w9XwA8RhTD///+KhTD///8PEUWsikWsM8DrOItNHIXJdBWL0TPAwekC86uLyoPhA/Oqi0UgigAPV8APEYUw////ioUw////DxFFrIpFrLgBAAAAX14PEYVA////x0WoAAAAAA8RhVD///9bDxGFYP///w8RhXD///8PEUWADxFFkGYP1kWgi+VdwiQAzMzMzMzMVYvsVleLfQgPtgeZi8iL8g+2RwEPpM4ImcHhCAvyC8gPtkcCD6TOCJnB4QgL8gvID7ZHAw+kzgiZweEIC/ILyA+2RwQPpM4ImcHhCAvyC8gPtkcFD6TOCJnB4QgL8gvID7ZHBg+kzgiZweEIC/ILyA+2RwcPpM4ImcHhCAvBC9ZfXl3CBADMzMzMzMzMzMzMVYvsg+wIi0UQSPfQmVOLXQiJRfiLRQyJVfzzD35d+I1LeFYz9mYPbNuNUHg7wXdLO9" & _
                                                "NyRyvYx0UQEAAAAFdmkIs8GI1ACIt0GPyLSPiLUPwzzyNN+DPWI1X8M/kz8ol8GPiJdBj8MUj4MVD8g20QAXXOX15bi+VdwgwAi9ONSBAr0A8QDPONSSAPEFHQZg/v0WYP29MPKMJmD+/BDxEE84PGBA8QQdBmD+/QDxFR0A8QTArgDxBR4GYP79FmD9vTDyjCZg/vwQ8RRArgDxBB4GYP78IPEUHgg/4QcqVeW4vlXcIMAMzMzMzMzMzMzMzMVYvsg+xsi0UIjVWUU1a7oAAAADP2i0gEiU34i0gIiU30i0gMiU3oi0gQiU38i0gUiU3wi0gYiU3si00Mg8ECiXXcV4s4K9OLQByJfeCJReSJTdiJXQyJVdQPH4AAAAAAg/4QcykPtnH+D7ZB/8HmCAvwD7YBweYIC/APtkEBweYIC/CDwQSJNBqJTdjrVI1eAYPmD41D/YPgD419lI08t4tMhZSLw4PgD4vxwcYPi1SFlIvBwcANM/DB6Qoz8YvCi8rByAfBwQ4zyMHqA41D+DPKi10Mg+APA/EDdIWUAzeJN+hpwv//i338i9fByguLz8HBBzPRi8/ByQb31yN97DPRiwwYg8MEi0XwA8ojRfwDzot14DP4i9aJXQzByg2LxsHACgP5A33kM9CLxsHIAjPQi0X4i8gjxjPOI030M8iLReyJReQD0YtF8ItN+IlF7ItF/IlF8ItF6APHiXX4i3XcA/qLVdRGiUX8i0X0iU30i03YiUXoiX3giXXcgfugAQAAD4LX/v//i0UIi034i1X8AUgEi030AUgIAVAQATiLTeiLVfABSAwBUBSLVeyLTeQBUBgBSBz/QGBfXluL5V3CCADMzMzMzMzMzMzMzMxVi+yB7OAAAABTVot1CLu" & _
                                                "gAQAAV4lduIsGiUXsi0YEiUXwi0YMi34IiUXgi0YQiUXUi0YUiUXQi0YYiUW0i0YciUWwi0YgiUXoi0YkiUX0i0YoiUXMi0YsiUXIi0YwiUXEi0Y0iUXAi0Y4iUWsi0Y8i3UMiX3Yjb0g////iUWoM8Ar+4lF3Il9oA8fgAAAAACD+BBzH1boFfz//4vIg8YIi8KJTQyJReSJDB+JRB8E6RMBAACNUAHHRQwAAAAAjUL9g+APi4zFIP///4uExST///+JRfiLwoPgD4lN/I2NIP///4uUxSD///+L+oucxST///+LRdyD4A+JVbzB5xiNBMGLy4lFpIvCD6zICAlFDItFvMHpCAv5i8sPrMgBiX3ki/rR6TPSC9DB5x8xVQwL+YtFvItN5A+s2AczzzFFDItF/MHrBzPLM9uJTeSLTfiL0Q+kwQPB6h3B4AML2YtN+AvQi0X8i/gPrMgTiVW8M9IL0MHpE4tFvDPCwecNi1X8C/mLTfgz3w+sygYzwsHpBotVDDPZi03kA9CLRdwTy4PA+YPgDwOUxSD///8TjMUk////i0WkAxCJVQwTSASJEIlN5IlIBOi0v///i1X0M/+LTeiL2g+kyhfB6wkL+sHhF4tV9AvZi03oiV38i9kPrNESiX34M/8L+cHqEjF9/DP/i03oweMOC9qLVfQxXfiL2Q+s0Q7B4xIL+cHqDjF9/Avai034i1W4M8uLXfyLfej31wMcEBNMEAQjfcSLVfSLRcj30iNF9CNVwDPQiU34i03MI03oi0X4M/mLTfAD3xPCA10ME0XkA12siV38E0WoM9uJRfiLReyL0A+syBzB4gTB6RwL2ItF7AvRi03wi/kPpMEeiVUMM9LB7wIL0cHgHgv4M98xVQwz0otN" & _
                                                "8Iv5i0XsD6TBGcHvBwvRweAZMVUMC/iLTdgz34tV4Iv5M33sI33UI03sM1XwM/kjVdCLReAjRfCLTcQz0ItFDAPfi334E8KJTayLTcCLVfwDVbSJTagTfbCLTcwDXfyJTcSLTciJTcCLTeiJTcyLTfSJffSLfdSJfbSLfdCJfbCLfdiJfdSLfeCJfdCLfeyJTciLyBNN+ItF3Ild7ECLXbiJfdiDwwiLffCJfeCLfaCJVeiJTfCJRdyJXbiB+yAEAAAPghv9//+LdQiLReyLfdgBBotF4BFOBIvKAX4Ii320EUYMi0XUAUYQi0XQEUYUAX4Yi0WwEUYcAU4gi0X0EUYki0XMAUYoi0XIEUYsi0XEAUYwi0XAEUY0i02sAU44i02oEU48/4bAAAAAX15bi+VdwggAzMzMzMzMzMzMzMzMzMxVi+yLRRBTVot1CI1IeFeLfQyNVng78XcEO9BzC41PeDvxdzA713IsK/i7EAAAACvwixQ4KxCLTDgEG0gEjUAIiVQw+IlMMPyD6wF15F9eW13CDACL141IEIveK9Ar2Cv+uAQAAACNdiCNSSAPEEHQDxBMN+BmD/vIDxFO4A8QTArgDxBB4GYP+8gPEUwL4IPoAXXSX15bXcIMAMzMzMzMVYvsi00MU4tdCFaDwxDHRQwEAAAAV4PBAw8fgAAAAAAPtkH+jVsgmY1JCIvwi/oPtkH1D6T3CJnB5ggD8Ilz0BP6iXvUD7ZB95mL8Iv6D7ZB+JkPpMIIweAIA/CJc9gT+ol73A+2QfqZi/CL+g+2QfkPpPcImcHmCAPwiXPgE/qJe+QPtkH8mYvwi/oPtkH7D6T3CJnB5ggD8Ilz6BP6g20MAYl77A+FdP///4tNCF9eW4FheP9/AADHQ" & _
                                                "XwAAAAAXcIIAMzMzMzMzMzMzMzMzFWL7IPsCFOLXQwPV8BWV4t9EIsTi/KLQwSLyGYPE0X4AzcTTwQ78nUGO8h1BOsYO8h3D3IEO/JzCbgBAAAAM9LrC2YPE0X4i0X4i1X8i30IiU8Ei00QiTeLcQgDcwiLSQwTSwwD8BPKO3MIdQU7Swx0IDtLDHcQcgU7cwhzCbgBAAAAM9LrC2YPE0X4i1X8i0X4iU8Mi00QiXcIi3EQA3MQi0kUE0sUA/ATyjtzEHUFO0sUdCA7SxR3EHIFO3MQcwm4AQAAADPS6wtmDxNF+ItV/ItF+IlPFIl3EItLGItbHIlNDItNEItxGAN1DItJHBPLA/ATyjt1DHUEO8t0LDvLdx1yBTt1DHMWiXcYuAEAAACJTxwz0l9eW4vlXcIMAGYPE0X4i1X8i0X4iXcYiU8cX15bi+VdwgwAzMzMzMzMVYvsi00MugMAAABTi10IVivZjUEYV4ldCA8fgAAAAACLNAOLXAMEi3gEiwg733cuciI78XcoO99yGncEO/FyFItdCIPoCIPqAXnVX14zwFtdwggAX16DyP9bXcIIAF9euAEAAABbXcIIAMzMzMzMzFWL7IPsEFOLXRC5QAAAAFaLdQgry1eLfQxmD27DiU0QiweLVwSJRfiJVfzzD35N+GYP88hmD9YO6MPG//+LTRCJRfCLRwiJVfSLVwyJRfiJVfzzD35N+GYPbsNmD/PI8w9+RfBmD+vIZg/WTgjojsb//4tNEIlF8ItHEIlV9ItXFIlF+IlV/PMPfk34Zg9uw2YP88jzD35F8GYP68hmD9ZOEOhZxv//i00QiUXwi0cYiVX0i1cciUX4iVX88w9+TfhmD27DZg/zyPMPfkXwZg/ryGYP1k4Y6C" & _
                                                "TG//9fXluL5V3CDADMzMzMzMzMzMzMzFWL7IPsKFOLXQwPV8BWi3UIV4sDagGJBotDBIlGBItDCIlGCItDDIlGDItDEIlGEItDFIlGFItDGIlGGItDHIlGHItDLIlF5ItDMIlF6ItDNIlF7ItDOIlF8ItDPIlF9I1F2FBQZg8TRdjHReAAAAAA6Jr+//+L+I1F2FBWVujd/P//i0swA/iLUzwzwAtDNIlF6I1F2GoBUIlN5ItLOFDHReAAAAAAiU3siVXwx0X0AAAAAOhX/v//A/iNRdhQVlbomvz//wP4x0XkAAAAAItDIA9XwIlF2ItDJIlF3ItDKIlF4ItDOIlF8ItDPGYPE0XoiUX0jUXYUFZW6GD8//8D+ItLJDPAi1M0C0MoiUXci0MwiUX4M8ALQyyJReCLQziJReiLQzyJRewzwAtDIIlF9I1F2FCJTdiLylZWiU3kiVXw6Bj8//+LUzQD+ItLLDPAC0MwD1fAiUXcM8ALQyCJRfCNRdhQVol9CIt7KFaJTdiJVeDHReQAAAAAZg8TReiJffToVwgAAClFCA9XwItDMLEgi1UMM/+JRdiLQzSJRdyLQziJReCLQzyLWyyJReSLQiCLUiRmDxNF6OhPxP//C/iNRdhQC9qJffBWiV30VugKCAAAi10MKUUIM8ALQziLSzSLUyyLezCJRdwzwAtDPIlN2ItLIIlF4ItDKIlN5LEg6OjD//8LQySJReiNRdhQVlaJVezHRfAAAAAAiX306LoHAACLfQgr+MdF4AAAAACLQziJRdiLQzyJRdyLQySJReSLQyiJReiLQyyJReyLQzSJRfSNRdhQVlbHRfAAAAAA6HgHAAAr+HkkDx9AAOgLt///UFZW6OP6//8D+HjvX15bi+V"
Private Const STR_ECC_THUNK3        As String = "dwggAZg8fRAAAhf91EVbo5rb//1DoAPz//4P4AXTc6Na2//9QVlboLgcAACv469rMzMzMzMzMzMzMVYvsi1UMgeyIAAAAM8lmkIsEygtEygR1RkGD+QRy8YtFCMcAAAAAAMdABAAAAADHQAgAAAAAx0AMAAAAAMdAEAAAAADHQBQAAAAAx0AYAAAAAMdAHAAAAACL5V3CDACLAg9XwImFeP///4tCBImFfP///4tCCIlFgItCDIlFhItCEIlFiItCFIlFjItCGIlFkItCHIlFlFaLdRBXM/9mDxNF4GYPE0XoiwaJRZiLRgSJRZyLRgiJRaCLRgyJRaSLRhCJRaiLRhSJRayLRhiJRbCLRhyJRbSNRZhQjYV4////Zg8TRfBQx0XYAQAAAIl93GYPE0W4Zg8TRcBmDxNFyGYPE0XQ6Nb6//+L0IXSD4S6AQAAU2ZmZg8fhAAAAAAAi414////D1fAg+EBZg8TRfiDyQB1L42FeP///1DovgMAAItF2IPgAYPIAA+EtgAAAFaNRdhQUOhE+f//i/iL2umoAAAAi0WYg+ABg8gAdSyNRZhQ6IcDAACLRbiD4AGDyAAPhAgBAABWjUW4UFDoDfn//4v4i9rp+gAAAIXSD46MAAAAjUWYUI2FeP///1BQ6GsFAACNhXj///9Q6D8DAACNRbhQjUXYUOgS+v//hcB5C1aNRdhQUOjD+P//jUW4UI1F2FBQ6DUFAACLRdiD4AGDyAB0EVaNRdhQUOif+P//i/iL2usGi138i334jUXYUOjqAgAAC/sPhJIAAACLRfCBTfQAAACAiUXw6YAAAACNhXj///9QjUWYUFDo3wQAAI1FmFDotgIAAI1F2FCNRbhQ6In5//+FwHkLVo1FuFBQ6Dr4" & _
                                                "//+NRdhQjUW4UFDorAQAAItFuIPgAYPIAHQRVo1FuFBQ6Bb4//+L+Iva6waLXfyLffiNRbhQ6GECAAAL+3QNi0XQgU3UAAAAgIlF0I1FmFCNhXj///9Q6CD5//+L0IXSD4VW/v//i33cW4tNCItF2IkBi0XgiUEIi0XkiUEMi0XoiUEQi0XsiUEUi0XwiXkEiUEYi0X0X4lBHF6L5V3CDADMzMzMzMzMzMzMzFWL7IPsVFMPV8AzyWYPE0XUi0XYVmYPE0XMi13QiUX4i0XUV4t9zIlN7IlF/A8fADP2jUH9g/kED1fAZg8TRfCLVfQPQ/A78Q+HLwEAAIvBiVXoi00QK8aNBMGLTfCJTfSLTeyJReSD/gQPg9gAAAD/cAT/MItFDP908AT/NPCNRaxQ6Bjk//8PEABmD37BDxFFzGYPc9gEA89mD37AiU28E8OJRcA7w3cPcgQ7z3MJuQEAAAAz0usOD1fAZg8TRdyLVeCLTdyLfdQDz4tF2BPQA038iU3EE1X4iVXIDxBFvA8RRcw70HcPcgQ7z3MJuAEAAAAzyesOD1fAZg8TRdyLTeCLRdwBRfSLVeiLReQT0YtN7EaLfcyD6AiJVeiJReQ78XcUi13YiV34i13UiV38i13Q6S7///+LRdiLXdCJRfiLRdSJRfyLRfSLdQiJPM6LffyJXM4EQYtd+IlF/IlV+IlN7IP5Bw+Cwv7//4l+OF+JXjxeW4vlXcIMAItF8OvJzMzMzMzMzMzMzMzMzMxVi+yLVQi4AwAAAA8fRAAAiwzCC0zCBHUFg+gBefKNSAGFyXUGM8BdwgQAVot0yviLVMr8i85XM/8LynQQDx8AD6zWAUfR6ovOC8p188HgBgPHX15dwgQAzMzMzMzMzMxVi" & _
                                                "+yD7AiLRQgPV8BTi9hmDxNF+IPAIDvDdjiLTfhWV4t9/IlNCItw+IPoCIvOi1AED6zRAQtNCNHqC9eJCIv+iVAEwecfx0UIAAAAADvDd9VfXluL5V3CBADMzMzMzMxVi+yD7FgPV8AzyVNmDxNF0ItF1GYPE0XIi1XMi13IVolF8ItF0FeJTdiJRfSJVewz9o1B/YP5BA9XwGYPE0XgD0PwO/EPh2sBAACLfQyLwSvGjQTHi33kiX38i33giUXciX34i/kr/jv3D4cLAQAA/3AE/zCLRQz/dPAE/zTwjUWoUOjI4f//DxAADxFFyItVzDv3czGLTdSL+ovBwegfAUX4i0XQg1X8AA+kwQHB7x8DwAv4M8ALwYlF5ItFyA+kwgEDwOsMi0XUi33QiUXki0XIA8OJRbgTVeyJVbw7Vex3D3IEO8NzCbgBAAAAM8nrDg9XwGYPE0Xoi03si0XoA8cTTeQDRfSJRcATTfCJTcQPEEW4DxFFyDtN5HcPcgQ7x3MJuAEAAAAzyesOD1fAZg8TReCLTeSLReABRfiLRdwRTfxGi03Yg+gIi13IiUXcO/F3F4tV1IlV8ItV0IlV9ItVzIlV7On4/v//i0XUi1XMiUXwi0XQiUX0i0X4i338i3UIiRzOi130iVTOBEGLVfCJVeyJRfSJffCJTdiD+QcPgon+//9fiV44iVY8XluL5V3CCACLfeSLReDrw8zMVYvsg+wMU4tdDA9XwFZXi30QixOL8otDBIvIZg8TRfQrNxtPBDvydQY7yHUE6xg7yHIPdwQ78nYJuAEAAAAz0usLZg8TRfSLRfSLVfiLfQiJTwSLTRCJN4tzCIl1+CtxCItLDItdEBtLDCvwi10MG8o7dfh1BTtLDHQgO0sMch" & _
                                                "B3BTtzCHYJuAEAAAAz0usLZg8TRfSLVfiLRfSJTwyLTRCJdwiLcxCJdfwrcRCLSxSLXRAbSxQr8ItdDBvKO3X8dQU7SxR0IDtLFHIQdwU7cxB2CbgBAAAAM9LrC2YPE0X0i1X4i0X0iU8UiXcQi0sYi/GLfRCLWxyJTQyLTRArcRiLyxtPHCvwi30IG8o7dQx1BDvLdCw7y3IddwU7dQx2Fol3GLgBAAAAiU8cM9JfXluL5V3CDABmDxNF9ItV+ItF9Il3GIlPHF9eW4vlXcIMAAAA" ' 20979, 17.4.2020 22:16:51

Private Const CF_SHA256_HASHSZ      As Long = 32
Private Const CF_SHA256_BLOCKSZ     As Long = 64
Private Const CF_SHA384_HASHSZ      As Long = 48
Private Const CF_SHA384_BLOCKSZ     As Long = 128
Private Const CF_SHA384_CONTEXTSZ   As Long = 200
Private Const LNG_HMAC_INNER_PAD    As Long = &H36
Private Const LNG_HMAC_OUTER_PAD    As Long = &H5C
Private Const LNG_CHACHA20POLY1305_TAG_SIZE As Long = 16

Private m_uEcc                  As UcsEccThunkData

Private Enum UcsEccPfnIndexEnum
    ucsPfnSecp256r1MakeKey
    ucsPfnSecp256r1SharedSecret
    ucsPfnCurve25519ScalarMultiply
    ucsPfnCurve25519ScalarMultBase
    ucsPfnSha256Init
    ucsPfnSha256Update
    ucsPfnSha256Final
    ucsPfnSha384Init
    ucsPfnSha384Update
    ucsPfnSha384Final
    ucsPfnChacha20Poly1305Encrypt
    ucsPfnChacha20Poly1305Decrypt
    [_ucsPfnMax]
End Enum

Private Type UcsEccThunkData
    Thunk               As Long
    Glob                As Long
    Pfn(0 To [_ucsPfnMax] - 1) As Long
    EccKeySize          As Long
    HashCtx(0 To CF_SHA384_CONTEXTSZ - 1) As Byte
    HashPad(0 To CF_SHA384_BLOCKSZ - 1) As Byte
    HashFinal(0 To CF_SHA384_HASHSZ - 1) As Byte
End Type

'=========================================================================
' Functions
'=========================================================================

Public Function EccInit() As Boolean
'    Dim baThunk()       As Byte
    Dim lOffset         As Long
    Dim lIdx            As Long
    
    If m_uEcc.Thunk = 0 Then
    With m_uEcc
        .EccKeySize = 32
        '--- prepare thunk/context in executable memory
        .Thunk = pvThunkAllocate(STR_ECC_THUNK1 & STR_ECC_THUNK2 & STR_ECC_THUNK3)
        .Glob = pvThunkAllocate(STR_ECC_GLOB)
        If .Thunk = 0 Or .Glob = 0 Then
            GoTo QH
        End If
        '--- init pfns from thunk addr + offsets stored at beginning of it
        For lIdx = 0 To UBound(.Pfn)
            Call CopyMemory(lOffset, ByVal UnsignedAdd(.Thunk, 4 * lIdx), 4)
            .Pfn(lIdx) = UnsignedAdd(.Thunk, lOffset)
        Next
        '--- init pfns trampolines
        Call pvPatchProto(AddressOf pvEccCallSecp256r1MakeKey)
        Call pvPatchProto(AddressOf pvEccCallSecp256r1SharedSecret)
        Call pvPatchProto(AddressOf pvEccCallCurve25519Multiply)
        Call pvPatchProto(AddressOf pvEccCallCurve25519MulBase)
        Call pvPatchProto(AddressOf pvHashCallSha256Init)
        Call pvPatchProto(AddressOf pvHashCallSha256Update)
        Call pvPatchProto(AddressOf pvHashCallSha256Final)
        Call pvPatchProto(AddressOf pvHashCallSha384Init)
        Call pvPatchProto(AddressOf pvHashCallSha384Update)
        Call pvPatchProto(AddressOf pvHashCallSha384Final)
        Call pvPatchProto(AddressOf pvAeadCallChacha20Poly1305Encrypt)
        Call pvPatchProto(AddressOf pvAeadCallChacha20Poly1305Decrypt)
        '--- init thunk's first 4 bytes -> global data in C/C++
        Call CopyMemory(ByVal .Thunk, .Glob, 4)
    End With
    End If
    '--- success
    EccInit = True
QH:
End Function

Public Function EccSecp256r1MakeKey(baPrivate() As Byte, baPublic() As Byte) As Boolean
    Const MAX_RETRIES   As Long = 16
    Dim lIdx            As Long
    
    ReDim baPrivate(0 To m_uEcc.EccKeySize - 1) As Byte
    ReDim baPublic(0 To m_uEcc.EccKeySize) As Byte
    For lIdx = 1 To MAX_RETRIES
        pvEccRandomBytes VarPtr(baPrivate(0)), m_uEcc.EccKeySize
        If pvEccCallSecp256r1MakeKey(m_uEcc.Pfn(ucsPfnSecp256r1MakeKey), VarPtr(baPublic(0)), VarPtr(baPrivate(0))) = 1 Then
            Exit For
        End If
    Next
    '--- success (or failure)
    EccSecp256r1MakeKey = (lIdx <= MAX_RETRIES)
End Function

Public Function EccSecp256r1SharedSecret(baPrivate() As Byte, baPublic() As Byte) As Byte()
    Dim baRetVal()      As Byte
    
    Debug.Assert UBound(baPrivate) >= m_uEcc.EccKeySize - 1
    Debug.Assert UBound(baPublic) >= m_uEcc.EccKeySize
    ReDim baRetVal(0 To m_uEcc.EccKeySize - 1) As Byte
    If pvEccCallSecp256r1SharedSecret(m_uEcc.Pfn(ucsPfnSecp256r1SharedSecret), VarPtr(baPublic(0)), VarPtr(baPrivate(0)), VarPtr(baRetVal(0))) = 0 Then
        GoTo QH
    End If
    EccSecp256r1SharedSecret = baRetVal
QH:
End Function

Public Function EccCurve25519MakeKey(baPrivate() As Byte, baPublic() As Byte) As Boolean
    ReDim baPrivate(0 To m_uEcc.EccKeySize - 1) As Byte
    ReDim baPublic(0 To m_uEcc.EccKeySize - 1) As Byte
    pvEccRandomBytes VarPtr(baPrivate(0)), m_uEcc.EccKeySize
    baPrivate(0) = baPrivate(0) And 248
    baPrivate(UBound(baPrivate)) = (baPrivate(UBound(baPrivate)) And 127) Or 64
    pvEccCallCurve25519MulBase m_uEcc.Pfn(ucsPfnCurve25519ScalarMultBase), VarPtr(baPublic(0)), VarPtr(baPrivate(0))
    '--- success
    EccCurve25519MakeKey = True
End Function

Public Function EccCurve25519SharedSecret(baPrivate() As Byte, baPublic() As Byte) As Byte()
    Dim baRetVal()      As Byte
    
    Debug.Assert UBound(baPrivate) >= m_uEcc.EccKeySize - 1
    Debug.Assert UBound(baPublic) >= m_uEcc.EccKeySize - 1
    ReDim baRetVal(0 To m_uEcc.EccKeySize - 1) As Byte
    pvEccCallSecp256r1SharedSecret m_uEcc.Pfn(ucsPfnCurve25519ScalarMultiply), VarPtr(baRetVal(0)), VarPtr(baPrivate(0)), VarPtr(baPublic(0))
    EccCurve25519SharedSecret = baRetVal
End Function

Public Function HashSha256(baInput() As Byte, ByVal lPos As Long, ByVal lSize As Long) As Byte()
    Dim lCtxPtr         As Long
    Dim lPtr            As Long
    Dim baRetVal()      As Byte
    
    With m_uEcc
        lCtxPtr = VarPtr(.HashCtx(0))
        If lSize > 0 Then
            lPtr = VarPtr(baInput(lPos))
        End If
        pvHashCallSha256Init .Pfn(ucsPfnSha256Init), lCtxPtr
        pvHashCallSha256Update .Pfn(ucsPfnSha256Update), lCtxPtr, lPtr, lSize
        ReDim baRetVal(0 To CF_SHA256_HASHSZ - 1) As Byte
        pvHashCallSha256Final .Pfn(ucsPfnSha256Final), lCtxPtr, VarPtr(baRetVal(0))
    End With
    HashSha256 = baRetVal
End Function

Public Function HashSha384(baInput() As Byte, ByVal lPos As Long, ByVal lSize As Long) As Byte()
    Dim lCtxPtr         As Long
    Dim lPtr            As Long
    Dim baRetVal()      As Byte
    
    With m_uEcc
        lCtxPtr = VarPtr(.HashCtx(0))
        If lSize > 0 Then
            lPtr = VarPtr(baInput(lPos))
        End If
        pvHashCallSha384Init .Pfn(ucsPfnSha384Init), lCtxPtr
        pvHashCallSha384Update .Pfn(ucsPfnSha384Update), lCtxPtr, lPtr, lSize
        ReDim baRetVal(0 To CF_SHA384_HASHSZ - 1) As Byte
        pvHashCallSha384Final .Pfn(ucsPfnSha384Final), lCtxPtr, VarPtr(baRetVal(0))
    End With
    HashSha384 = baRetVal
End Function

Public Function HmacSha256(baKey() As Byte, baInput() As Byte, ByVal lPos As Long, ByVal lSize As Long) As Byte()
    Dim lCtxPtr         As Long
    Dim lPtr            As Long
    Dim lIdx            As Long
    
    Debug.Assert UBound(baKey) < CF_SHA256_BLOCKSZ
    With m_uEcc
        lCtxPtr = VarPtr(.HashCtx(0))
        If lSize > 0 Then
            lPtr = VarPtr(baInput(lPos))
        End If
        '-- inner hash
        pvHashCallSha256Init .Pfn(ucsPfnSha256Init), lCtxPtr
        Call FillMemory(.HashPad(0), CF_SHA256_BLOCKSZ, LNG_HMAC_INNER_PAD)
        For lIdx = 0 To UBound(baKey)
            .HashPad(lIdx) = baKey(lIdx) Xor LNG_HMAC_INNER_PAD
        Next
        pvHashCallSha256Update .Pfn(ucsPfnSha256Update), lCtxPtr, VarPtr(.HashPad(0)), CF_SHA256_BLOCKSZ
        pvHashCallSha256Update .Pfn(ucsPfnSha256Update), lCtxPtr, lPtr, lSize
        pvHashCallSha256Final .Pfn(ucsPfnSha256Final), lCtxPtr, VarPtr(.HashFinal(0))
        '-- outer hash
        pvHashCallSha256Init .Pfn(ucsPfnSha256Init), lCtxPtr
        Call FillMemory(.HashPad(0), CF_SHA256_BLOCKSZ, LNG_HMAC_OUTER_PAD)
        For lIdx = 0 To UBound(baKey)
            .HashPad(lIdx) = baKey(lIdx) Xor LNG_HMAC_OUTER_PAD
        Next
        pvHashCallSha256Update .Pfn(ucsPfnSha256Update), lCtxPtr, VarPtr(.HashPad(0)), CF_SHA256_BLOCKSZ
        pvHashCallSha256Update .Pfn(ucsPfnSha256Update), lCtxPtr, VarPtr(.HashFinal(0)), CF_SHA256_HASHSZ
        ReDim baRetVal(0 To CF_SHA256_HASHSZ - 1) As Byte
        pvHashCallSha256Final .Pfn(ucsPfnSha256Final), lCtxPtr, VarPtr(baRetVal(0))
    End With
    HmacSha256 = baRetVal
End Function

Public Function HmacSha384(baKey() As Byte, baInput() As Byte, ByVal lPos As Long, ByVal lSize As Long) As Byte()
    Dim lCtxPtr         As Long
    Dim lPtr            As Long
    Dim lIdx            As Long
    
    Debug.Assert UBound(baKey) < CF_SHA384_BLOCKSZ
    With m_uEcc
        lCtxPtr = VarPtr(.HashCtx(0))
        If lSize > 0 Then
            lPtr = VarPtr(baInput(lPos))
        End If
        '-- inner hash
        pvHashCallSha384Init .Pfn(ucsPfnSha384Init), lCtxPtr
        Call FillMemory(.HashPad(0), CF_SHA384_BLOCKSZ, LNG_HMAC_INNER_PAD)
        For lIdx = 0 To UBound(baKey)
            .HashPad(lIdx) = baKey(lIdx) Xor LNG_HMAC_INNER_PAD
        Next
        pvHashCallSha384Update .Pfn(ucsPfnSha384Update), lCtxPtr, VarPtr(.HashPad(0)), CF_SHA384_BLOCKSZ
        pvHashCallSha384Update .Pfn(ucsPfnSha384Update), lCtxPtr, lPtr, lSize
        pvHashCallSha384Final .Pfn(ucsPfnSha384Final), lCtxPtr, VarPtr(.HashFinal(0))
        '-- outer hash
        pvHashCallSha384Init .Pfn(ucsPfnSha384Init), lCtxPtr
        Call FillMemory(.HashPad(0), CF_SHA384_BLOCKSZ, LNG_HMAC_OUTER_PAD)
        For lIdx = 0 To UBound(baKey)
            .HashPad(lIdx) = baKey(lIdx) Xor LNG_HMAC_OUTER_PAD
        Next
        pvHashCallSha384Update .Pfn(ucsPfnSha384Update), lCtxPtr, VarPtr(.HashPad(0)), CF_SHA384_BLOCKSZ
        pvHashCallSha384Update .Pfn(ucsPfnSha384Update), lCtxPtr, VarPtr(.HashFinal(0)), CF_SHA384_HASHSZ
        ReDim baRetVal(0 To CF_SHA384_HASHSZ - 1) As Byte
        pvHashCallSha384Final .Pfn(ucsPfnSha384Final), lCtxPtr, VarPtr(baRetVal(0))
    End With
    HmacSha384 = baRetVal
End Function

Public Function AeadChacha20Poly1305Encrypt(baNonce() As Byte, baKey() As Byte, _
            baAad() As Byte, ByVal lAadPos As Long, ByVal lAdSize As Long, _
            baBuffer() As Byte, ByVal lPos As Long, ByVal lSize As Long) As Boolean
    If pvAeadCallChacha20Poly1305Encrypt(m_uEcc.Pfn(ucsPfnChacha20Poly1305Encrypt), VarPtr(baKey(0)), VarPtr(baNonce(0)), _
            VarPtr(baAad(lAadPos)), lAdSize, _
            VarPtr(baBuffer(lPos)), lSize, _
            VarPtr(baBuffer(lPos)), VarPtr(baBuffer(lPos + lSize))) = 0 Or True Then
        AeadChacha20Poly1305Encrypt = True
    End If
End Function

Public Function AeadChacha20Poly1305Decrypt(baNonce() As Byte, baKey() As Byte, _
            baAad() As Byte, ByVal lAadPos As Long, ByVal lAdSize As Long, _
            baBuffer() As Byte, ByVal lPos As Long, ByVal lSize As Long) As Boolean
    If pvAeadCallChacha20Poly1305Decrypt(m_uEcc.Pfn(ucsPfnChacha20Poly1305Decrypt), VarPtr(baKey(0)), VarPtr(baNonce(0)), _
            VarPtr(baAad(lAadPos)), lAdSize, _
            VarPtr(baBuffer(lPos)), lSize - LNG_CHACHA20POLY1305_TAG_SIZE, _
            VarPtr(baBuffer(lPos + lSize - LNG_CHACHA20POLY1305_TAG_SIZE)), VarPtr(baBuffer(lPos))) = 0 Then
        AeadChacha20Poly1305Decrypt = True
    End If
End Function

'= private ===============================================================

Private Function pvEccCallSecp256r1MakeKey(ByVal Pfn As Long, ByVal lPubKeyPtr As Long, ByVal lPrivKeyPtr As Long) As Long
    ' int ecc_make_key(uint8_t p_publicKey[ECC_BYTES+1], uint8_t p_privateKey[ECC_BYTES]);
End Function

Private Function pvEccCallSecp256r1SharedSecret(ByVal Pfn As Long, ByVal lPubKeyPtr As Long, ByVal lPrivKeyPtr As Long, ByVal lSecretPtr As Long) As Long
    ' int ecdh_shared_secret(const uint8_t p_publicKey[ECC_BYTES+1], const uint8_t p_privateKey[ECC_BYTES], uint8_t p_secret[ECC_BYTES]);
End Function

Private Function pvEccCallCurve25519Multiply(ByVal Pfn As Long, ByVal lSecretPtr As Long, ByVal lPubKeyPtr As Long, ByVal lPrivKeyPtr As Long) As Long
    ' void cf_curve25519_mul(uint8_t out[32], const uint8_t priv[32], const uint8_t pub[32])
End Function

Private Function pvEccCallCurve25519MulBase(ByVal Pfn As Long, ByVal lPubKeyPtr As Long, ByVal lPrivKeyPtr As Long) As Long
    ' void cf_curve25519_mul_base(uint8_t out[32], const uint8_t priv[32])
End Function

Private Function pvHashCallSha256Init(ByVal Pfn As Long, ByVal lCtxPtr As Long) As Long
    ' void cf_sha256_init(cf_sha256_context *ctx)
End Function

Private Function pvHashCallSha256Update(ByVal Pfn As Long, ByVal lCtxPtr As Long, ByVal lDataPtr As Long, ByVal lSize As Long) As Long
    ' void cf_sha256_update(cf_sha256_context *ctx, const void *data, size_t nbytes)
End Function

Private Function pvHashCallSha256Final(ByVal Pfn As Long, ByVal lCtxPtr As Long, ByVal lHashPtr As Long) As Long
    ' void cf_sha256_digest_final(cf_sha256_context *ctx, uint8_t hash[CF_SHA256_HASHSZ])
End Function

Private Function pvHashCallSha384Init(ByVal Pfn As Long, ByVal lCtxPtr As Long) As Long
    ' void cf_sha384_init(cf_sha384_context *ctx)
End Function

Private Function pvHashCallSha384Update(ByVal Pfn As Long, ByVal lCtxPtr As Long, ByVal lDataPtr As Long, ByVal lSize As Long) As Long
    ' void cf_sha384_update(cf_sha384_context *ctx, const void *data, size_t nbytes)
End Function

Private Function pvHashCallSha384Final(ByVal Pfn As Long, ByVal lCtxPtr As Long, ByVal lHashPtr As Long) As Long
    ' void cf_sha384_digest_final(cf_sha384_context *ctx, uint8_t hash[CF_SHA384_HASHSZ])
End Function

Private Function pvAeadCallChacha20Poly1305Encrypt(ByVal Pfn As Long, ByVal lKeyPtr As Long, ByVal lNoncePtr As Long, _
            ByVal lHeaderPtr As Long, ByVal lHeaderSize As Long, _
            ByVal lPlaintTextPtr As Long, ByVal lPlaintTextSize As Long, _
            ByVal lCipherTextPtr As Long, ByVal lTagPtr As Long) As Long
    'void cf_chacha20poly1305_encrypt(const uint8_t key[32],
    '                                 const uint8_t nonce[12],
    '                                 const uint8_t *header, size_t nheader,
    '                                 const uint8_t *plaintext, size_t nbytes,
    '                                 uint8_t *ciphertext,
    '                                 uint8_t tag[16])
End Function

Private Function pvAeadCallChacha20Poly1305Decrypt(ByVal Pfn As Long, ByVal lKeyPtr As Long, ByVal lNoncePtr As Long, _
            ByVal lHeaderPtr As Long, ByVal lHeaderSize As Long, _
            ByVal lCipherTextPtr As Long, ByVal lCipherTextSize As Long, _
            ByVal lTagPtr As Long, ByVal lPlaintTextPtr As Long) As Long
    'int cf_chacha20poly1305_decrypt(const uint8_t key[32],
    '                                const uint8_t nonce[12],
    '                                const uint8_t *header, size_t nheader,
    '                                const uint8_t *ciphertext, size_t nbytes,
    '                                const uint8_t tag[16],
    '                                uint8_t *plaintext)
End Function
Private Sub pvEccRandomBytes(ByVal lPtr As Long, ByVal lSize As Long)
    Dim hProv           As Long
    
    If CryptAcquireContext(hProv, 0, 0, PROV_RSA_FULL, CRYPT_VERIFYCONTEXT) <> 0 Then
        Call CryptGenRandom(hProv, lSize, lPtr)
        Call CryptReleaseContext(hProv, 0)
    End If
End Sub

Private Function pvThunkAllocate(sText As String, Optional ByVal Size As Long) As Long
    Static Map(0 To &H3FF) As Long
    Dim baInput()       As Byte
    Dim lIdx            As Long
    Dim lChar           As Long
    Dim lPtr            As Long
    
    pvThunkAllocate = VirtualAlloc(0, IIf(Size > 0, Size, (Len(sText) \ 4) * 3), MEM_COMMIT, PAGE_EXECUTE_READWRITE)
    If pvThunkAllocate = 0 Then
        Exit Function
    End If
    '--- init decoding maps
    If Map(65) = 0 Then
        baInput = StrConv("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/", vbFromUnicode)
        For lIdx = 0 To UBound(baInput)
            lChar = baInput(lIdx)
            Map(&H0 + lChar) = lIdx * (2 ^ 2)
            Map(&H100 + lChar) = (lIdx And &H30) \ (2 ^ 4) Or (lIdx And &HF) * (2 ^ 12)
            Map(&H200 + lChar) = (lIdx And &H3) * (2 ^ 22) Or (lIdx And &H3C) * (2 ^ 6)
            Map(&H300 + lChar) = lIdx * (2 ^ 16)
        Next
    End If
    '--- base64 decode loop
    baInput = StrConv(Replace(Replace(sText, vbCr, vbNullString), vbLf, vbNullString) & "===", vbFromUnicode)
    lPtr = pvThunkAllocate
    For lIdx = 0 To UBound(baInput) - 3 Step 4
        lChar = Map(baInput(lIdx + 0)) Or Map(&H100 + baInput(lIdx + 1)) Or Map(&H200 + baInput(lIdx + 2)) Or Map(&H300 + baInput(lIdx + 3))
        Call CopyMemory(ByVal lPtr, lChar, 3)
        lPtr = UnsignedAdd(lPtr, 3)
    Next
End Function

Private Sub pvPatchProto(ByVal Pfn As Long)
    Dim bInIDE          As Boolean
 
    Debug.Assert pvSetTrue(bInIDE)
    If bInIDE Then
        Call CopyMemory(Pfn, ByVal UnsignedAdd(Pfn, &H16), 4)
    Else
        Call VirtualProtect(Pfn, 8, PAGE_EXECUTE_READWRITE, 0)
    End If
    ' 0:  58                      pop    eax
    ' 1:  59                      pop    ecx
    ' 2:  50                      push   eax
    ' 3:  ff e1                   jmp    ecx
    ' 5:  90                      nop
    ' 6:  90                      nop
    ' 7:  90                      nop
    Call CopyMemory(ByVal Pfn, -802975883527609.7192@, 8)
End Sub

Private Function pvSetTrue(bValue As Boolean) As Boolean
    bValue = True
    pvSetTrue = True
End Function

Private Function UnsignedAdd(ByVal lUnsignedPtr As Long, ByVal lSignedOffset As Long) As Long
    '--- note: safely add *signed* offset to *unsigned* ptr for *unsigned* retval w/o overflow in LARGEADDRESSAWARE processes
    UnsignedAdd = ((lUnsignedPtr Xor &H80000000) + lSignedOffset) Xor &H80000000
End Function
